### PR TITLE
Review of PDG architecture

### PR DESCRIPTION
**Pull request by sarthou**
- Facilitates the addition of Human/Robot/Object
- Make code easier to read
- Allows the perception of an object from several sources
- Adding an intelligent agent to deduce the facts from the OM2M object

### CODE REVIEW

**Review by GregoireMilliez — COMMENTED** [review]
I don't really get why you remove IoTObject, 
Also if you don't use them anymore, maybe it should be removed from Toaster-lib too?

**Review by GregoireMilliez — COMMENTED** [review]
This is a good idea to add the publish function to the reader, it simplifies the code and make it easier to read :)

**Comment by sarthou** [comment]
IoTObject was too specific and can't be merge with other objects type. This type is in my opinion only a bad patch.
It will be removed from Toaster-lib too

**Comment by GregoireMilliez** [comment]
Ok, I see.
I don't really know about OM2M and IoT stuff so I trust you on that one :)

**Comment by sarthou** [comment]
ok :)
It is good to merge for you ?

**Comment by GregoireMilliez** [comment]
Looks like good work to me.
I couldn't read everything in detail but I think it does make things easier.
Maybe another step toward clean code would be to uniform the notations and add some developer guidelines...

As far as I have seen, it is good to merge yes :)

**Comment by sarthou** [comment]
I tried to unify the annotation but it is really long and complicated ...
Thanks for your review !

**Comment by GregoireMilliez** [comment]
Yes I know... Even I was not always consistent with myself ^^

Writting guidlines somewhere could help, as more and more people are developping in TOASTER, to at least avoid an improving number of divergent notations...
Anyways, I know it's hard to do, it was just a suggestion :)

**Pull request merged**
